### ISSUE TITLE
Suggested replacement of inefficient part of pipeline (subset_aligned_reads)

### ISSUE THREAD

**Issue by medmaca** [kzeglinski/nabseq_nf#10] opened 2024-08-05 09:30 UTC
Hi, firstly thank you for creating the nabseq_nf pipeline.

I've been running the nabseq pipeline on Seqera/Tower and noticed that the biggest bottleneck is the `subset_aligned_reads ` step, which for larger libraries was taking many days to complete.  I have a potential work around which I'll attach here for your consideration **which I think significantly speeds up the pipeline** and I believe generates the same output.

It involves 3 main changes.

## Modifying the reference files to remove spaces in headers (replace with @ symbols):
[modified_references.zip](https://github.com/user-attachments/files/16493611/modified_references.zip)

This is required so that the SAM files produced in the my minimap2 don't have duplicates sequence names

## Modifying minimap2.nf
[minimap2.zip](https://github.com/user-attachments/files/16493660/minimap2.zip)

Changing the output from minimap2 from PAF to SAM, only retaining the best matches.  This relies on using the modified reference files that have no spaces in the headers to generate SAM files with correct format for use by samtools in the next step.

```
// adapted from the nf-core module: https://github.com/nf-core/modules/tree/master/modules/nf-core/minimap2/align
// (replaced meta$id with just meta) because sample name is our only metadata
// also set --secondary=no since we don't want secondary alignments and removed the bam output option (& samtools) since it was not needed 
// finally, changed to also emit the reads it aligned (because we need them in the next step of subsetting)
// idk why 

process minimap2_alignment {
    tag "$prefix"
    label 'process_high'

    conda (params.enable_conda ? 'bioconda::minimap2=2.24' : null)
    container "${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ?
        'https://depot.galaxyproject.org/singularity/minimap2%3A2.24--h7132678_1' :
        'quay.io/biocontainers/minimap2:2.24--h7132678_1' }"

    input:
    tuple val(meta), path(reads)
    path reference

    output:
    tuple val(meta), path("*.sam"), path(reads), optional: true, emit: paf_reads
    tuple val(meta), path(reads), path(reference), path("*.sam"), optional: true, emit: for_racon

    when:
    task.ext.when == null || task.ext.when

    script:
    def args = task.ext.args ?: ''
    
    // allow for a bunch of metadata (although the first element should be sample name)
    if(meta instanceof Collection) {
        prefix = meta[0]
    } else {
        prefix = meta
    }

    """
    minimap2 \\
        $args \\
        -t $task.cpus \\
        --secondary=no \\
        -x map-ont \\
        "${reference ?: reads}" \\
        "$reads" \\
        -o ${prefix}.sam \\
        --sam-hit-only \\
        -a
    """
}

```

## Modifying select_ab_reads.nf

[select_ab_reads.zip](https://github.com/user-attachments/files/16493692/select_ab_reads.zip)

Modified to use samtools to convert from SAM to fastq format.  

```
// do minimap2 alignment to the specified reference
// then, use seqkit to select the reads that align

include { minimap2_alignment } from '../modules/local/minimap2' 

process subset_aligned_reads {
    tag {prefix}
    label 'process_high'

    conda (params.enable_conda ? 'bioconda::seqkit=2.3.1' : null)
    // container "${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ?
    //     'https://depot.galaxyproject.org/singularity/seqkit%3A2.3.1--h9ee0642_0' :
    //     'quay.io/biocontainers/seqkit:2.3.1--h9ee0642_0' }"

    container "${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ?
    'https://depot.galaxyproject.org/singularity/samtools:1.20--h50ea8bc_1' :
    'quay.io/biocontainers/samtools:1.20--h50ea8bc_1' }"

    input:
    tuple val(meta), path(sam_file), path(reads)

    output:
    tuple val(meta), path("*_ab_reads.fastq")

    script:

    // allow for a bunch of metadata (although the first element should be sample name)
    if(meta instanceof Collection) {
        prefix = meta[0]
    } else {
        prefix = meta
    }

    """
    # aligned read names are the first column of the PAF file
    # cut -f1 $sam_file > "${prefix}_ab_read_names.txt"
    
    # use these names as a pattern for seqkit grep to find
    # seqkit grep --by-name --use-regexp --threads ${task.cpus} \
    #-f "${prefix}_ab_read_names.txt" \
    #$reads \
    # -o "${prefix}_ab_reads.fastq"

    samtools fastq -@ ${task.cpus} $sam_file > ${prefix}_ab_reads.fastq

    """

}

workflow select_ab_reads {
    take:
        ab_selection_input
    
    main:
        // split input into reads + meta data and then reference file
        ab_selection_input
            .map{it[-1]}
            .set{reference}

        ab_selection_input
            .map{it[0..-2]}
            .map{tuple([it[0], it[2], it[3]], it[1])}
            .set{minimap2_input}

        // align reads using minimap2
        minimap2_alignment(minimap2_input, reference)

        // subset the aligned reads using seqkit
        ab_reads = subset_aligned_reads(minimap2_alignment.out.paf_reads)
        
    emit:
        ab_reads

}

```

I hope this is helpful.

**Comment by kzeglinski** [comment] 2024-08-09 01:59
Hey thank you so much! We usually only run the pipeline with 20-40 hybridomas, each of which have ~100k reads, so I never noticed how horribly this step scales as the number of reads increases. I really appreciate you taking the time to share your improved code and have now incorporated it into the pipeline.

Also, just on the topic of performance, I think one other place where things can be optimised is the consensus calling step. Back in 2021 when we developed this pipeline, the combination of racon + medaka was required to generate good consensus sequences, especially when there were only like 5-20 reads per transcript. But now that we have kit 14, dorado v5 basecalling models etc I think it's a bit of overkill. I've had good results in some preliminary tests (100% accuracy achieved with 3-5 reads in most cases) just using [abPOA](https://github.com/yangao07/abPOA) which is _super_ fast. When I have some time in the next few months I'm planning on doing some formal testing of this and will probably ultimately replace the racon + medaka consensus with abPOA. Just wanted to let you know in case that might be helpful for you!

**Comment by gitkemp** [comment] 2024-08-09 15:42
@medmaca @kzeglinski 
Hi Guys, I am trying out the nabseq workflow and implementing it my lab, I am not a programmer or bio-informatician, 
I have Dell precession tower work station with RTX4060. What changes should I need to make it work on my computer and any suggestions regarding the cDNA sequencing kit that comes with the minion starter pack. I will use this kit for the first sequencing experiment.

**Comment by medmaca** [comment] 2024-08-12 07:17
> Hey thank you so much! We usually only run the pipeline with 20-40 hybridomas, each of which have ~100k reads, so I never noticed how horribly this step scales as the number of reads increases. I really appreciate you taking the time to share your improved code and have now incorporated it into the pipeline.
> 
> Also, just on the topic of performance, I think one other place where things can be optimised is the consensus calling step. Back in 2021 when we developed this pipeline, the combination of racon + medaka was required to generate good consensus sequences, especially when there were only like 5-20 reads per transcript. But now that we have kit 14, dorado v5 basecalling models etc I think it's a bit of overkill. I've had good results in some preliminary tests (100% accuracy achieved with 3-5 reads in most cases) just using [abPOA](https://github.com/yangao07/abPOA) which is _super_ fast. When I have some time in the next few months I'm planning on doing some formal testing of this and will probably ultimately replace the racon + medaka consensus with abPOA. Just wanted to let you know in case that might be helpful for you!

Glad it was useful, and thank you for the heads up regarding `abPOA`.

**Comment by gitkemp** [comment] 2024-11-14 15:08
Hi,
I have used this tool on the EPI2Me GUI, with cDNA PCR sequencing kit V14(Sqk-PCs114) I get the following error, could you help with this, the base calls were on fast read mode, I am currently running a HAC base call again to get more accurate base calls, but I suspect I may get the same error:
N E X T F L O W  ~  version 23.04.2
Launching `/mnt/c/Users/Lab/epi2melabs/workflows/kzeglinski/nabseq_nf/main.nf` [silly_hopper] DSL2 - revision: 42b7f5d537
O---o
 O-o    NAb-seq: a nextflow pipeline for the analysis of
  O     Oxford Nanopore sequencing data from hybridomas and
 o-O    single B cells.
o---O
O---o   Version: v0.4.1
 O-o    For more information about how to use NAb-seq,
  O     check out our github:
 o-O    https://github.com/kzeglinski/nabseq_nf/
o---O
-----------------------------------------------------------
read directory              : /mnt/c/Nabseq/12470_4G12_13NOV2024/12470_4G12_mAb_seq_test_13NOV2024/12470_4G12_13NOV2024/20241113_1355_MN47512_FAZ88376_1828e4a1/fastq_pass
number of consensus seqs    : 999
sample sheet                : /mnt/c/Nabseq/12470_4G12_13NOV2024/12470_4G12_mAb_seq_test_13NOV2024/12470_4G12_13NOV2024/20241113_1355_MN47512_FAZ88376_1828e4a1/sample_sheet_FAZ88376_20241113_1359_1828e4a1.csv
medaka model                : r1041_e82_400bps_sup_v4.3.0
output directory            : /mnt/c/Nabseq/12470_4G12_13NOV2024/nabsefast read 14nov2024 test
[a0/5fc1e1] Submitted process > validate_params
[fd/8c76f8] Submitted process > versions:create_versions
[4f/489341] Submitted process > parse_sample_sheet:concat_reads (null)
[67/905a49] Submitted process > versions:cutadapt
[2c/45f9ea] Submitted process > nanocomp ([null])
[0a/b57177] Submitted process > versions:fastq_to_fasta
[b8/5f7aea] Submitted process > versions:igblast
[20/31ad6a] Submitted process > versions:medaka
ERROR ~ Error executing process > 'nanocomp ([null])'
Caused by:
  Process `nanocomp ([null])` terminated with an error exit status (1)
Command executed:
  NanoComp \
       \
      -t 2 \
      --fastq null.fastq.gz \
      --prefix "report_null_"
Command exit status:
  1
Command output:
  (empty)
Command error:
  Unable to find image 'quay.io/biocontainers/nanocomp:1.19.3--pyhdfd78af_0' locally
  1.19.3--pyhdfd78af_0: Pulling from biocontainers/nanocomp
  73349e34840e: Pulling fs layer
  acab339ca1e8: Pulling fs layer
  91d67b998356: Pulling fs layer
  acab339ca1e8: Download complete
  73349e34840e: Verifying Checksum
  73349e34840e: Download complete
  73349e34840e: Pull complete
  acab339ca1e8: Pull complete
  91d67b998356: Download complete
  91d67b998356: Pull complete
  Digest: sha256:1263e702b2974903f99bb3066a1cd2c1ecc3e7508706e353d408a84623e107eb
  Status: Downloaded newer image for quay.io/biocontainers/nanocomp:1.19.3--pyhdfd78af_0
  Fatal: No reads found in input.
Work dir:
  /mnt/c/Users/Lab/epi2melabs/instances/nabseq_nf_01JCNJQRQHZDE2M8FTBJ42BW5F/work/2c/45f9eab7ec31f9d90e41e00b8b09ea
Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
 -- Check '/mnt/c/Users/Lab/epi2melabs/instances/nabseq_nf_01JCNJQRQHZDE2M8FTBJ42BW5F/nextflow.log' file for details

**Comment by kzeglinski** [comment] 2024-11-15 04:11
Hi, thanks for reaching out! Looking at the error message, I think there is an issue with the sample sheet format due to the sample name being 'NULL'. Are you able to share your sample sheet so I can check it? Thanks

**Comment by gitkemp** [comment] 2024-11-15 04:49
the data set is quite large to share. I got it to work by making an additional sample csv file with the format you suggested barcode, sample name, species, report group. Example "FAZ88376_pass_1828e4a1_43fc195a_0, sample name, Mus musculus, 0"etc.
But I find that the output directory fastq is either large if all the files are conatonated to 1 file , the adaptor and TSO sequences are still intact, and there is no actual antibody sequence identification or antibody sequence file generated. 
[FAZ88376_pass_1828e4a1_43fc195a_114.zip](https://github.com/user-attachments/files/17769729/FAZ88376_pass_1828e4a1_43fc195a_114.zip)
I have the smallest file that I could share
[Uploading sample sheet_SM.csv…]()

**Comment by gitkemp** [comment] 2024-11-15 04:49
the data set is quite large to share. I got it to work by making an additional sample csv file with the format you suggested barcode, sample name, species, report group. Example "FAZ88376_pass_1828e4a1_43fc195a_0, sample name, Mus musculus, 0"etc.
But I find that the output directory fastq is either large if all the files are conatonated to 1 file , the adaptor and TSO sequences are still intact, and there is no actual antibody sequence identification or antibody sequence file generated. 
[FAZ88376_pass_1828e4a1_43fc195a_114.zip](https://github.com/user-attachments/files/17769729/FAZ88376_pass_1828e4a1_43fc195a_114.zip)
I have the smallest file that I could share
[Uploading sample sheet_SM.csv…]()

**Comment by gitkemp** [comment] 2024-11-15 04:53
Do you do any pre-processing before using Nab seq on Epi2me?

**Comment by kzeglinski** [comment] 2024-11-15 05:00
Hi no worries that the data is large, I shouldn't need that as I think the issue here is with the sample sheet. 
I can't seem to download the sample sheet csv, but just a couple of things from the example line you shared:

- 'FAZ88376_pass_1828e4a1_43fc195a_0' is the name of a fastq file rather than a barcode name. The barcode names should be in the format of like 'barcode01' or 'barcode20' etc and depend on the barcodes you used with the kit. You should get files/folders named like that after basecalling. Can you confirm what your directory structure is? What I mean by that is within the folder with your fastqs, do you have a folder for each barcode?
- for the sample name, please ensure that there is no space, for example use 'sample_name' or 'sample-name' or 'samplename' instead of 'sample name'
- for the organism, it should be 'mouse' rather than 'Mus musculus'

And no, I don't do any pre-processing before running the pipeline (other than basecalling, which is done as part of the run)

**Comment by gitkemp** [comment] 2024-11-15 05:13
Thanks for the quick reply, for this run I used the cDNA PCR kit for one hybridoma sample, without any barcode kit. I ran the sequencing run for 24 hours with fast call mode (lol very new to this so did not know how to set up a HAC read mode the first time)
The data folder has both Fastq and POd files. The fastqfolder has 114 individual folder (FAZ88376_pass_1828e4a1_43fc195a_0 to 114) with a fastq for each folder.
So in the latest run I changed the sample sheet to some thing like this:
![image](https://github.com/user-attachments/assets/36f23e20-1c3d-4266-9f1e-0d420fce7ec7)
[sample sheet_SM.csv](https://github.com/user-attachments/files/17769941/sample.sheet_SM.csv)

**Comment by kzeglinski** [comment] 2024-11-15 05:54
Ohh ok! So to process this with NAb-seq we need either (1) all of the fastq files to be merged into one file (so one file for each sample) OR (2) all of the fastq files to be contained within a single folder (one folder for each sample). From basecalling you usually get one of those output formats. I'm not quite sure why you have a folder for each fastq, minKNOW has never done that for me (usually it's just one folder with all the fastq files in it). 

You can use the command `cat */*.fastq > all_files.fastq` to combine them all into a single file, or most likely the HAC basecalling you're running will output into one of the file structures outlined above.

Then in the sample sheet, you'd only need:
all_files,12470_4G12,mouse,1
(assuming that you have one single fastq called 'all_files')

**Comment by gitkemp** [comment] 2024-11-15 06:32
thanks the cat command did not work for me :(, 
on the other hand how long do you suggest to run the sequencing run, I had initially set it up for 24 hours, but, stopped it after 19hours, when the data generated reached 64 gigs. Also do you recommend setting up minimum read length of 880bp and a max of 5kbp during the initial set up?

**Comment by gitkemp** [comment] 2024-11-16 03:07
got a long way than yesterday, another new error:
Command exit status:
  1
Command output:
  (empty)
Command error:
  BLAST query/options error: Germline annotation database mouse/mouse_V could not be found in [internal_data] directory
  Please refer to the BLAST+ user manual.
Work dir:
  /mnt/c/Users/shara/epi2melabs/instances/nabseq_nf_01JCSDM3XQMARNEYTEHJJA9PYM/work/c7/1fa22d6fb1df7d3461dc7bb4fd485d
Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
 -- Check '/mnt/c/Users/shara/epi2melabs/instances/nabseq_nf_01JCSDM3XQMARNEYTEHJJA9PYM/nextflow.log' file for details

**Comment by gitkemp** [comment] 2024-11-18 15:02
for this particular error, is there a particular file format that the V, D, J , C database file should be in?

**Closed** 2024-12-05 05:25 UTC
